[2024-01-30 16:38:47 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16618] Error ping verified: yiilian_core::Error(IO, Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }, 38.12.39.175:16697)
[2024-01-30 16:53:17 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16665] Error ping verified: yiilian_core::Error(Transatcion, "Transaction of query exists: 51.223.71.238:1024 ")
[2024-01-30 17:00:57 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16604] Error ping verified: yiilian_core::Error(Transatcion, "Transaction of query exists: 196.188.180.163:26 569")

[2024-01-30 21:07:15 DEBUG yiilian_dht::net::server] send_to error: [16680] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 81.61.145.16:0)
[2024-01-30 22:06:18 DEBUG yiilian_dht::net::server] send_to error: [16676] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 174.105.49.93:0)
[2024-01-30 22:41:44 DEBUG yiilian_dht::net::server] send_to error: [16632] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 190.90.21.85:0)
[2024-01-30 22:41:51 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16632] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 190.90.21.85:0)
[2024-01-30 22:42:01 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16632] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 190.90.21.85:0)
[2024-01-30 22:42:11 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16632] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 190.90.21.85:0)
[2024-01-30 22:42:21 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16632] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 190.90.21.85:0)
[2024-01-30 22:42:31 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16632] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 190.90.21.85:0)
[2024-01-30 22:42:41 DEBUG yiilian_dht::dht::periodic_buddy_ping] [16632] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 190.90.21.85:0)
[2024-01-30 22:51:27 DEBUG yiilian_dht::net::server] send_to error: [16676] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 174.105.49.93:0)
[2024-01-30 23:21:27 DEBUG yiilian_dht::net::server] send_to error: [16676] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 174.105.49.93:0)

2024-01-31T03:39:56.823229699+00:00 DEBUG yiilian_dht::dht::ping_routers - [16632] error: yiilian_core::Error(Net, Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }, "Failed to resolve host dht.transmissionbt.com:6881")
2024-01-31T03:39:56.823534379+00:00 DEBUG yiilian_dht::dht::ping_routers - [16632] error: yiilian_core::Error(Net, Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }, "Failed to resolve host router.utorrent.com:6881")
2024-01-31T03:39:56.823557804+00:00 DEBUG yiilian_dht::dht::ping_routers - [16689] error: yiilian_core::Error(Net, Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }, "Failed to resolve host router.utorrent.com:6881")
2024-01-31T03:39:56.823574561+00:00 DEBUG yiilian_dht::dht::ping_routers - [16542] error: yiilian_core::Error(Net, Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }, "Failed to resolve host dht.transmissionbt.com:6881")
2024-01-31T03:39:56.823585816+00:00 DEBUG yiilian_dht::dht::ping_routers - [16542] error: yiilian_core::Error(Net, Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }, "Failed to resolve host router.utorrent.com:6881")
2024-01-31T04:29:05.336966703+00:00 DEBUG yiilian_dht::net::server - send_to error: [16643] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 122.102.135.86:0)
2024-01-31T08:47:39.816126507+00:00 DEBUG yiilian_dht::net::server - send_to error: [16503] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 201.157.55.66:0)
2024-01-31T12:42:47.442971105+00:00 DEBUG yiilian_dht::net::server - send_to error: [16593] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 122.102.135.86:0)
2024-01-31T12:42:47.444413533+00:00 DEBUG yiilian_dht::net::server - send_to error: [16565] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 122.102.135.86:0)
2024-01-31T12:42:47.447848523+00:00 DEBUG yiilian_dht::net::server - send_to error: [16505] yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 122.102.135.86:0)

2024-01-31T16:21:45.332429251+00:00 ERROR yiilian_core::net::udp::send_to - send_to error: [16505] Os { code: 22, kind: InvalidInput, message: "Invalid argument" } remote:68.192.67.80:0 
 data:
b"d1:t2:\xd2#1:y1:q1:q4:ping1:ad2:id20:\xa81Q\x14bc\x92_t@\x7f\x81\xd2\x1c\xf5-v0\xa9\x98ee"
2024-01-31T16:21:45.333129360+00:00 DEBUG yiilian_dht::dht::periodic_buddy_ping - [16505] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 68.192.67.80:0)
2024-01-31T16:21:55.334802917+00:00 ERROR yiilian_core::net::udp::send_to - send_to error: [16505] Os { code: 22, kind: InvalidInput, message: "Invalid argument" } remote:68.192.67.80:0 
 data:
b"d1:q4:ping1:y1:q1:ad2:id20:\xa81Q\x14bc\x92_t@\x7f\x81\xd2\x1c\xf5-v0\xa9\x98e1:t2:i~e"
2024-01-31T16:21:55.334966211+00:00 DEBUG yiilian_dht::dht::periodic_buddy_ping - [16505] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 68.192.67.80:0)
2024-01-31T16:22:05.337252221+00:00 ERROR yiilian_core::net::udp::send_to - send_to error: [16505] Os { code: 22, kind: InvalidInput, message: "Invalid argument" } remote:68.192.67.80:0 
 data:
b"d1:y1:q1:q4:ping1:ad2:id20:\xa81Q\x14bc\x92_t@\x7f\x81\xd2\x1c\xf5-v0\xa9\x98e1:t2:>Ke"
2024-01-31T16:22:05.337473685+00:00 DEBUG yiilian_dht::dht::periodic_buddy_ping - [16505] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 68.192.67.80:0)
2024-01-31T16:22:15.338615112+00:00 ERROR yiilian_core::net::udp::send_to - send_to error: [16505] Os { code: 22, kind: InvalidInput, message: "Invalid argument" } remote:68.192.67.80:0 
 data:
b"d1:q4:ping1:ad2:id20:\xa81Q\x14bc\x92_t@\x7f\x81\xd2\x1c\xf5-v0\xa9\x98e1:y1:q1:t2:\xfe\x1fe"
2024-01-31T16:22:15.338776893+00:00 DEBUG yiilian_dht::dht::periodic_buddy_ping - [16505] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 68.192.67.80:0)
2024-01-31T16:22:25.340472795+00:00 ERROR yiilian_core::net::udp::send_to - send_to error: [16505] Os { code: 22, kind: InvalidInput, message: "Invalid argument" } remote:68.192.67.80:0 
 data:
b"d1:t2:\x92\x981:q4:ping1:y1:q1:ad2:id20:\xa81Q\x14bc\x92_t@\x7f\x81\xd2\x1c\xf5-v0\xa9\x98ee"
2024-01-31T16:22:25.340792866+00:00 DEBUG yiilian_dht::dht::periodic_buddy_ping - [16505] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 68.192.67.80:0)
2024-01-31T16:22:35.342151596+00:00 ERROR yiilian_core::net::udp::send_to - send_to error: [16505] Os { code: 22, kind: InvalidInput, message: "Invalid argument" } remote:68.192.67.80:0 
 data:
b"d1:y1:q1:t2:\xd0\xfa1:ad2:id20:\xa81Q\x14bc\x92_t@\x7f\x81\xd2\x1c\xf5-v0\xa9\x98e1:q4:pinge"
2024-01-31T16:22:35.342592519+00:00 DEBUG yiilian_dht::dht::periodic_buddy_ping - [16505] Error ping unverified: yiilian_core::Error(IO, Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, 68.192.67.80:0)


2024-01-31T21:15:25.365241154+00:00 ERROR yiilian_dht::net::server - send_to error: [16546] yiilian_core::Error(General, "send_to address is invalid: 190.60.33.138:0")
 req:
Request { body: KrpcBody { kind: Query(GetPeers(GetPeers { t: TransactionId(b"\x83\xa7"), v: Some(b"LT\x01/"), ip: None, ro: None, id: fa911dd7c6e86572dd6da5d2709f292518c93b0f, info_hash: fa916247ba984314be461e29f36a16c05045b17e })), data: b"d1:ad2:id20:\xfa\x91\x1d\xd7\xc6\xe8er\xddm\xa5\xd2p\x9f)%\x18\xc9;\x0f9:info_hash20:\xfa\x91bG\xba\x98C\x14\xbeF\x1e)\xf3j\x16\xc0PE\xb1~e1:q9:get_peers1:t2:\x83\xa71:v4:LT\x01/1:y1:qe" }, remote_addr: 190.60.33.138:0, local_addr: 0.0.0.0:16546 }
2024-01-31T21:45:56.793181400+00:00 ERROR yiilian_dht::net::server - send_to error: [16628] yiilian_core::Error(General, "send_to address is invalid: 179.1.68.43:0")
 req:
Request { body: KrpcBody { kind: Query(GetPeers(GetPeers { t: TransactionId(b"\xbf\x9f"), v: Some(b"LT\x01/"), ip: None, ro: None, id: 81bc8086f6058cc24afc686419701af99386ee1e, info_hash: 89096ead14e774e7ca04fd6d4af491de8d2e24b4 })), data: b"d1:ad2:id20:\x81\xbc\x80\x86\xf6\x05\x8c\xc2J\xfchd\x19p\x1a\xf9\x93\x86\xee\x1e9:info_hash20:\x89\tn\xad\x14\xe7t\xe7\xca\x04\xfdmJ\xf4\x91\xde\x8d.$\xb4e1:q9:get_peers1:t2:\xbf\x9f1:v4:LT\x01/1:y1:qe" }, remote_addr: 179.1.68.43:0, local_addr: 0.0.0.0:16628 }
2024-02-01T01:41:11.146438291+00:00 ERROR yiilian_dht::net::server - send_to error: [16590] yiilian_core::Error(General, "send_to address is invalid: 190.60.33.138:0")
 req:
Request { body: KrpcBody { kind: Query(GetPeers(GetPeers { t: TransactionId(b"G\xf7"), v: Some(b"LT\x01/"), ip: None, ro: None, id: 86125682f317130c516cc471fb014a4e2d6cbff4, info_hash: 861232ced02a7cc0c617182d5749e17bef613a51 })), data: b"d1:ad2:id20:\x86\x12V\x82\xf3\x17\x13\x0cQl\xc4q\xfb\x01JN-l\xbf\xf49:info_hash20:\x86\x122\xce\xd0*|\xc0\xc6\x17\x18-WI\xe1{\xefa:Qe1:q9:get_peers1:t2:G\xf71:v4:LT\x01/1:y1:qe" }, remote_addr: 190.60.33.138:0, local_addr: 0.0.0.0:16590 }

2024-02-03T09:45:36.102559947+00:00 DEBUG yiilian_dht::dht::ping_routers - [16534] error: yiilian_core::Error(Net, Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }, "Failed to resolve host router.utorrent.com:6881")
2024-02-03T09:45:36.102571144+00:00 DEBUG yiilian_dht::dht::ping_routers - [16569] error: yiilian_core::Error(Net, Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }, "Failed to resolve host dht.transmissionbt.com:6881")
2024-02-03T16:45:35.819410940+00:00 DEBUG yiilian_dht::dht::ping_routers - [16512] error: yiilian_core::Error(Conntrack, Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }, 67.215.246.10:6881, "send_to resulted in PermissionDenied. Is conntrack table full?")
2024-02-04T04:44:28.983239128+00:00 ERROR yiilian_core::common::shutdown - Error watching shutdown_rx : RecvError(())
2024-02-04T04:44:28.983399232+00:00 ERROR yiilian_core::common::shutdown - Error watching shutdown_rx : RecvError(())
2024-02-04T04:44:28.983421607+00:00 ERROR yiilian_core::common::shutdown - Error watching shutdown_rx : RecvError(())
2024-02-04T04:44:28.991452401+00:00 ERROR yiilian_core::common::shutdown - Error watching shutdown_rx : RecvError(())
2024-02-04T04:44:28.991706695+00:00 ERROR yiilian_core::common::shutdown - Error watching shutdown_rx : RecvError(())

thread 'main' panicked at yiilian-dht/src/common/id.rs:21:47:
range end index 20 out of range for slice of length 19